export enum ActionType {
  MOVE_CELL = "MOVE_CELL",
  UPDATE_CELL = "UPDATE_CELL",
  INSERT_CELL_AFTER = "INSERT_CELL_AFTER",
  DELETE_CELL = "DELETE_CELL",
  BUNDLE_START = "BUNDLE_START",
  BUNDLE_COMPLETE = "BUNDLE_COMPLETE",
  SET_CELLS_STATE = "SET_CELLS_STATE",
}
